# This file is safe for a public repository.
# It only defines the Directus service and uses variables
# that will be injected by the Railway environment.

services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile.prod
    
    # Railway handles health checks and restart policies.
    # Railway also handles port mapping automatically.
    
    environment:
      # --- Core Directus Secrets (Set in Railway UI) ---
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}

      # --- Database Connection (Connects to your Railway PostGIS) ---
      DB_CLIENT: "pg"
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}

      # --- Cache Connection (Connects to your Railway Redis) ---
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"

      # --- Cloudflare R2 Storage (Set in Railway UI) ---
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_FORCE_PATH_STYLE: ${STORAGE_S3_FORCE_PATH_STYLE}

      # --- Email Configuration (Set in Railway UI) ---
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      # --- Other Configurations ---
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      PASSWORD_RESET_URL_ALLOW_LIST: ${PASSWORD_RESET_URL_ALLOW_LIST}
